package dev.csl.foliamines

import java.io.File

import dev.csl.foliamines.FoliaMines.Companion.plugin

import org.bukkit.configuration.file.YamlConfiguration

object Configurations {
    val minesConfigFile = File(plugin.dataFolder.toString() + File.separator + "mines.yml")

    fun createMinesConfig(): YamlConfiguration {
        if (plugin.dataFolder.exists() and this.minesConfigFile.exists()) return YamlConfiguration.loadConfiguration(this.minesConfigFile)

        var firstLoad = false

        if (!plugin.dataFolder.exists()) {
            plugin.dataFolder.mkdir()
            this.minesConfigFile.createNewFile()
            firstLoad = true
        } else if (!this.minesConfigFile.exists()) {
            this.minesConfigFile.createNewFile()
            firstLoad = true
        }

        val minesConfig = YamlConfiguration.loadConfiguration(this.minesConfigFile)
        if (firstLoad) {
            minesConfig.options().setHeader(listOf("DO NOT EDIT FILE, GENERATED BY FOLIAMINES"))
            minesConfig.createSection("mines")
            minesConfig.save(this.minesConfigFile)
        }

        return minesConfig
    }

    fun saveMinesConfig(configuration: YamlConfiguration) {
        configuration.save(this.minesConfigFile)
    }
}